export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_FAILED_NETWORK = 'LOGIN_FAILED_NETWORK';
export const LOGIN_FAILED_AKUN = 'LOGIN_FAILED_AKUN';
// export const CREATEID = 'CREATEID';
// export const CREATEID_SUCCESS = 'CREATEID_SUCCESS';
// export const CREATEID_FAILED = 'CREATEID_FAILED';
// export const CREATEID_SET_TOKEN = 'CREATEID_SET_TOKEN';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_FAILED_NETWORK = 'LOGOUT_FAILED_NETWORK';
export const LOGOUT_FAILED_AKUN = 'LOGOUT_FAILED_AKUN';
