export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const SET_AUTH = 'SET_AUTH';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';

export const REFERAL = 'REFERAL';
export const REFERAL_SUCCESS = 'REFERAL_SUCCESS';
export const REFERAL_FAILED = 'REFERAL_FAILED';

export const OTP = 'OTP';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILED = 'OTP_FAILED';

export const OTPRESEND = 'OTPRESEND';
export const OTPRESEND_SUCCESS = 'OTPRESEND_SUCCESS';
export const OTPRESEND_FAILED = 'OTPRESEND_FAILED';

export const LISTPRODUCT = 'LISTPRODUCT';
export const LISTPRODUCT_SUCCESS = 'LISTPRODUCT_SUCCESS';
export const LISTPRODUCT_FAILED = 'LISTPRODUCT_FAILED';

export const LISTPRODUCTDISCOUNT = 'LISTPRODUCTDISCOUNT';
export const LISTPRODUCTDISCOUNT_SUCCESS = 'LISTPRODUCTDISCOUNT_SUCCESS';
export const LISTPRODUCTDISCOUNT_FAILED = 'LISTPRODUCTDISCOUNT_FAILED';

export const PRODUCTDETAIL = 'PRODUCTDETAIL';
export const PRODUCTDETAIL_SUCCESS = 'PRODUCTDETAIL_SUCCESS';
export const PRODUCTDETAIL_FAILED = 'PRODUCTDETAIL_FAILED';

export const CREATEID = 'CREATEID';
export const CREATEID_SUCCESS = 'CREATEID_SUCCESS';
export const CREATEID_FAILED = 'CREATEID_FAILED';
export const CREATEID_SET_TOKEN = 'CREATEID_SET_TOKEN';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
