// {"accuracy": "2.0",
//  "agent_akusisi": 15,
//  "distributor": "",
//  "fintech": "",
//  "foto_dalam": "/9j/4AAQSkZJRgABAQAAAQABAA",
//  "foto_luar": "",
//  "foto_selfie": "",
// "hp": "67676494649",
//  "jenis_toko": "Cash",
//   "ket2_akusisi": "",
//   "ket_aktivasi": "Tidak",
//    "ket_akusisi": "Install",
//    "ket_lain": "",
//    "kota": "bzzhzhsjnsnsnsj",
//    "kulkas": "Ada",
//    "latitude": "-6.2095106",
//    "le_code": "123456789011111555",
//    "lokasi": "Didalam Gang(Perumahan)",
//    "longitude": "106.8323223",
//    "nama_toko": "ghHahhaba",
//    "note_akusisi": "hz",
//     "parkir": "Parkir Mobil",
//     "pjp": "Selasa",
//     "plafond": "",
//     "plang": "Tidak",
//     "provinsi": "hzhshshshshs",
//     "sales": "sbbsbsbsbajba",
//     "ukuran": "Besar"
// }
